TWEAK_NAME = DoABarrelWall
DoABarrelWall_FILES = Tweak.xm
DoABarrelWall_CFLAGS = -fobjc-arc
DoABarrelWall_FRAMEWORKS = UIKit
DoABarrelWall_EXTRA_FRAMEWORKS = Cephei 
ADDITIONAL_CFLAGS += -DTHEOS_LEAN_AND_MEAN
ADDITIONAL_CFLAGS += -std=gnu++11 -Wno-c++11-extensions

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
