TWEAK_NAME = RotateWall
RotateWall_FILES = Tweak.xm
RotateWall_CFLAGS = -fobjc-arc
RotateWall_FRAMEWORKS = UIKit
RotateWall_EXTRA_FRAMEWORKS = Cephei 
ADDITIONAL_CFLAGS += -DTHEOS_LEAN_AND_MEAN
ADDITIONAL_CFLAGS += -std=gnu++11 -Wno-c++11-extensions

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
